customer_list:
    path: /customers
    controller: App\Controller\CustomerController:indexAction
    methods: [GET]
    
customer_create:
    path: /customers
    controller: App\Controller\CustomerController:createAction
    methods: [POST]

product_list:
    path: /products
    controller: App\Controller\ProductController:indexAction
    methods: [GET]
    
product_create:
    path: /products
    controller: App\Controller\ProductController:createAction
    methods: [POST]

cart_show:
    path: /customers/{id}/cart
    controller: App\Controller\CartController:showAction
    methods: [GET]
    requirements:
        id: '\d+'
    
cart_create:
    path: /customers/cart
    controller: App\Controller\CartController:createAction
    methods: [POST]

cart_update:
    path: /customers/cart/{customerId}/cart
    controller: App\Controller\CartController:updateAction
    methods: [PATCH]
    requirements:
        customerId: '\d+'

cart_delete:
    path: /customers/{customerId}/cart/{cartId}
    controller: App\Controller\CartController:deleteAction
    methods: [DELETE]
    requirements:
        customerId: '\d+'
        cartId:  '\d+'
